# See https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 1m #Default
  issues-exit-code: 1 #Default
  tests: true #Default

linters:
  enable:
    - misspell
    - goimports
    - golint
    - stylecheck
    - unconvert
    - dupl
    - gosec
    - scopelint
    - nakedret
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - lll
    - maligned
    - prealloc
    - unparam
    - errcheck

linters-settings:
  misspell:
    locale: US
    #ignore-words:
    #  - someword
  goimports:
    local-prefixes: github.com/heroku/docker-registry-client
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 14
  lll:
    # max line length, lines longer will be reported. Default is 120.
    line-length: 130
  maligned:
    suggest-new: true
